Started GET "/" for 127.0.0.1 at 2021-02-14 21:00:32 -0600
  
PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
pg (1.2.3) lib/pg.rb:58:in `initialize'
pg (1.2.3) lib/pg.rb:58:in `new'
pg (1.2.3) lib/pg.rb:58:in `connect'
activerecord (6.0.3.5) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.5) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.5) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.5) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.5) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.5) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 127.0.0.1 at 2021-02-14 21:01:34 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 30.3ms | Allocations: 294)
Completed 200 OK in 43ms (Views: 35.6ms | ActiveRecord: 0.0ms | Allocations: 4268)


  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (1.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to DeviseCreateUsers (20210215030156)
  [1m[35m (0.9ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (29.5ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to DeviseCreateUsers (20210215030156)
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (18.4ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[35m (0.4ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (1.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (1.5ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (0.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (5450.1ms)[0m  [1m[35mDROP DATABASE IF EXISTS "vwb_development"[0m
  [1m[35m (1.5ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (1.2ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "environment"]]
  [1m[35m (142.8ms)[0m  [1m[35mDROP DATABASE IF EXISTS "vwb_development"[0m
  [1m[35m (2047.2ms)[0m  [1m[35mCREATE DATABASE "vwb_development" ENCODING = 'unicode'[0m
  [1m[35m (26.0ms)[0m  [1m[35mCREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)[0m
  [1m[35m (12.5ms)[0m  [1m[35mCREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to DeviseCreateUsers (20210215030156)
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (101.1ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "email" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "remember_created_at" timestamp, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[35m (5.6ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")[0m
  [1m[35m (7.6ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_reset_password_token" ON "users"  ("reset_password_token")[0m
  [1m[36mprimary::SchemaMigration Create (1.0ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20210215030156"]]
  [1m[35m (0.9ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.1ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[36mActiveRecord::InternalMetadata Create (1.2ms)[0m  [1m[32mINSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"[0m  [["key", "environment"], ["value", "development"], ["created_at", "2021-02-15 03:09:08.523081"], ["updated_at", "2021-02-15 03:09:08.523081"]]
  [1m[35m (0.6ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Started GET "/" for 127.0.0.1 at 2021-02-14 21:10:16 -0600
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 7.1ms | Allocations: 294)
Completed 200 OK in 18ms (Views: 10.8ms | ActiveRecord: 0.0ms | Allocations: 4267)


Started GET "/user" for 127.0.0.1 at 2021-02-14 21:10:20 -0600
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users" for 127.0.0.1 at 2021-02-14 21:11:32 -0600
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users/signup" for 127.0.0.1 at 2021-02-14 21:11:38 -0600
  
ActionController::RoutingError (No route matches [GET] "/users/signup"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users/signup" for 127.0.0.1 at 2021-02-14 21:12:15 -0600
  [1m[35m (2.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/users/signup"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/user" for 127.0.0.1 at 2021-02-14 21:15:56 -0600
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for ::1 at 2021-02-14 21:16:13 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 10.3ms | Allocations: 183)
Completed 200 OK in 16ms (Views: 12.1ms | ActiveRecord: 0.0ms | Allocations: 3482)


Started GET "/users/new" for ::1 at 2021-02-14 21:16:17 -0600
  
ActionController::RoutingError (No route matches [GET] "/users/new"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/user" for ::1 at 2021-02-14 21:16:21 -0600
  
ActionController::RoutingError (No route matches [GET] "/user"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users" for ::1 at 2021-02-14 21:16:29 -0600
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users/signin" for ::1 at 2021-02-14 21:16:34 -0600
  
ActionController::RoutingError (No route matches [GET] "/users/signin"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users/sign_up" for ::1 at 2021-02-14 21:16:41 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.3/app/views/devise/registrations/new.html.erb within layouts/application
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.3/app/views/devise/shared/_error_messages.html.erb (Duration: 11.0ms | Allocations: 195)
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.3/app/views/devise/shared/_links.html.erb (Duration: 35.9ms | Allocations: 507)
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.3/app/views/devise/registrations/new.html.erb within layouts/application (Duration: 288.1ms | Allocations: 7424)
[Webpacker] Compiling...
[Webpacker] Compiled all packs in /mnt/c/Files/学习资料/Spring 2021/CSCE 431/VWB-MemberTracker1/vwb/public/packs
[Webpacker] /home/entao/.rbenv/versions/2.7.0/bin/ruby: warning: shebang line ending with \r may cause problems

[Webpacker] Hash: 76145d9ce4575ebaa29b
Version: webpack 4.46.0
Time: 2051ms
Built at: 02/14/2021 9:16:47 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-c229f7c7014cf8c8d494.js    124 KiB  application  [emitted] [immutable]  application
js/application-c229f7c7014cf8c8d494.js.map    139 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-c229f7c7014cf8c8d494.js js/application-c229f7c7014cf8c8d494.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/packs/application.js] 749 bytes {application} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 3 hidden modules

Completed 200 OK in 5919ms (Views: 5900.7ms | ActiveRecord: 8.3ms | Allocations: 38562)


  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateIdentifies (20210215032411)
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (20.9ms)[0m  [1m[35mCREATE TABLE "identifies" ("id" bigserial primary key, "user_id" integer, "provider" text, "uid" text, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[36mprimary::SchemaMigration Create (0.7ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20210215032411"]]
  [1m[35m (2.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.5ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (1.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
DEPRECATION WARNING: Using `bin/rake routes` is deprecated and will be removed in Rails 6.1. Use `bin/rails routes` instead.
 (called from load at /home/entao/.rbenv/versions/2.7.0/bin/rake:23)
Started GET "/users/sign_up" for ::1 at 2021-02-14 21:52:58 -0600
  
RuntimeError (You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed.):
  
app/models/user.rb:4:in `<class:User>'
app/models/user.rb:3:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/users/sign_up" for ::1 at 2021-02-14 21:54:18 -0600
  [1m[35m (1.5ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.5ms | Allocations: 198)
  Rendered devise/shared/_links.html.erb (Duration: 1.2ms | Allocations: 616)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 48.5ms | Allocations: 5127)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 1304ms (Views: 1279.4ms | ActiveRecord: 8.0ms | Allocations: 39356)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 21:54:21 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 21:54:21 -0600
Started GET "/users/auth/google_oauth2/callback?state=d4a3557ab11c5e07a45645487e4de27f25e76bdba8e4dfdd&code=4%2F0AY0e-g76u1sD-SgzEti2-fPnD7CbPm0r5zjDj2g08O1K3V8GVvIpkS6yuoT4bg2POcJ8qA&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=consent" for ::1 at 2021-02-14 21:54:24 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started POST "/users" for ::1 at 2021-02-14 21:54:51 -0600
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"authenticity_token"=>"yfx6E7542imh6yhtPAWoguTcwtuBPBm0Fv92vUTFAPYKNmqSYJaPTSu/fjxG3AIdgMKuIrh73bEEJVkyZzm9bg==", "user"=>{"email"=>"entao2000@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Exists? (3.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2[0m  [["email", "entao2000@gmail.com"], ["LIMIT", 1]]
  [1m[36mUser Create (2.0ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["email", "entao2000@gmail.com"], ["encrypted_password", "$2a$12$4O3Il2ZqrG3KaBb.VoNv0ex6av8UcKOEQ4lU6KYtg9BRGyWjdZ212"], ["created_at", "2021-02-15 03:54:51.882158"], ["updated_at", "2021-02-15 03:54:51.882158"]]
  [1m[35m (1.6ms)[0m  [1m[35mCOMMIT[0m
Redirected to http://localhost:3000/
Completed 302 Found in 345ms (ActiveRecord: 7.4ms | Allocations: 10713)


Started GET "/" for ::1 at 2021-02-14 21:54:51 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 6.8ms | Allocations: 182)
Completed 200 OK in 10ms (Views: 9.2ms | ActiveRecord: 0.0ms | Allocations: 997)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 21:55:03 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 21:55:03 -0600
Started GET "/users/auth/google_oauth2/callback?state=83dfe0ecbc785a7441944aa60e6b1f8505e1768d2c012562&code=4%2F0AY0e-g7HB3s2MHEe7YTd5LiFPlM-Ls7kpEwkqyPMEcUEZJ4R2pR1AODzufxERUelGeZNXg&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=consent" for ::1 at 2021-02-14 21:55:06 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2/callback?state=83dfe0ecbc785a7441944aa60e6b1f8505e1768d2c012562&code=4%2F0AY0e-g5KbPYaa4QGSN-Guc5qQqwqPJrTVldb9c8wpFe1McEIDvM_t5CG3F6p8GErKiAc3w&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=consent" for ::1 at 2021-02-14 21:55:52 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/sign_in" for ::1 at 2021-02-14 22:04:54 -0600
Processing by Devise::SessionsController#new as HTML
  [1m[36mUser Load (2.1ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 38ms (ActiveRecord: 18.7ms | Allocations: 6662)


Started GET "/" for ::1 at 2021-02-14 22:04:54 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 7.2ms | Allocations: 179)
Completed 200 OK in 14ms (Views: 12.5ms | ActiveRecord: 0.0ms | Allocations: 962)


Started GET "/users/sign_in" for ::1 at 2021-02-14 22:04:54 -0600
Processing by Devise::SessionsController#new as HTML
  [1m[36mUser Load (0.8ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 11ms (ActiveRecord: 0.8ms | Allocations: 1882)


Started GET "/" for ::1 at 2021-02-14 22:04:54 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.8ms | Allocations: 7)
Completed 200 OK in 12ms (Views: 11.2ms | ActiveRecord: 0.0ms | Allocations: 460)


Started GET "/users/sign_in" for ::1 at 2021-02-14 22:05:10 -0600
Processing by Devise::SessionsController#new as HTML
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 15ms (ActiveRecord: 0.6ms | Allocations: 1896)


Started GET "/" for ::1 at 2021-02-14 22:05:10 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.8ms | Allocations: 7)
Completed 200 OK in 11ms (Views: 10.4ms | ActiveRecord: 0.0ms | Allocations: 468)


Started GET "/users/sign_in" for ::1 at 2021-02-14 22:05:10 -0600
Processing by Devise::SessionsController#new as HTML
  [1m[36mUser Load (0.9ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 27ms (ActiveRecord: 0.9ms | Allocations: 1877)


Started GET "/" for ::1 at 2021-02-14 22:05:10 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.5ms | Allocations: 7)
Completed 200 OK in 3ms (Views: 2.0ms | ActiveRecord: 0.0ms | Allocations: 449)


Started GET "/users/sign_up" for ::1 at 2021-02-14 22:05:22 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 1.4ms | Allocations: 189)
  Rendered devise/shared/_links.html.erb (Duration: 2.8ms | Allocations: 550)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 40.9ms | Allocations: 2399)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 61ms (Views: 59.2ms | ActiveRecord: 0.0ms | Allocations: 8934)


Started GET "/users/sign_in" for ::1 at 2021-02-14 22:05:25 -0600
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (Duration: 0.5ms | Allocations: 281)
  Rendered devise/sessions/new.html.erb within layouts/application (Duration: 55.0ms | Allocations: 1913)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 75ms (Views: 72.8ms | ActiveRecord: 0.0ms | Allocations: 7820)


Started POST "/users/sign_in" for ::1 at 2021-02-14 22:05:28 -0600
Processing by Devise::SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"dZIxGS5nX7aqEhitw2WIEq1m5FVnNy5di60FRTX3UcH98tONth8FA3nz9ToDwXv3kCRHASLK7pKiASzcJ6bsTQ==", "user"=>{"email"=>"entao2000@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
  [1m[36mUser Load (1.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["email", "entao2000@gmail.com"], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Completed 302 Found in 246ms (ActiveRecord: 1.4ms | Allocations: 6103)


Started GET "/" for ::1 at 2021-02-14 22:05:28 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.7ms | Allocations: 7)
Completed 200 OK in 8ms (Views: 7.5ms | ActiveRecord: 0.0ms | Allocations: 406)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 23:52:00 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 23:52:00 -0600
Started GET "/users/auth/google_oauth2/callback?state=97af7f379865598ec2ad55781e4de38d4b22247e31afb0f3&code=4/0AY0e-g7p6HJbj-gPisj9IRPl0lWfU0HcbxLGCgkkJmagNMQiklTz3akLAh_MdU3Kn8DW4A&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20openid&authuser=1&hd=tamu.edu&prompt=consent" for ::1 at 2021-02-14 23:52:02 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 23:54:55 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-14 23:54:55 -0600
Started GET "/users/auth/google_oauth2/callback?state=5e782272a3677b0b5fa0171825a6be42ceab62e8aec673e6&code=4%2F0AY0e-g5IUlzwPU6dz79oFoT3e0V9tFvsUJuAVds_LdmK_uzc3U2GoZVRa9U50mmFJ4256A&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=consent" for ::1 at 2021-02-14 23:54:58 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/sign_up" for ::1 at 2021-02-14 23:57:15 -0600
Processing by Devise::RegistrationsController#new as HTML
  [1m[36mUser Load (2.8ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 45ms (ActiveRecord: 24.5ms | Allocations: 6518)


Started GET "/" for ::1 at 2021-02-14 23:57:15 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 4.7ms | Allocations: 178)
Completed 200 OK in 9ms (Views: 6.6ms | ActiveRecord: 0.0ms | Allocations: 921)


Started GET "/users/sign_up" for ::1 at 2021-02-14 23:57:31 -0600
Processing by Devise::RegistrationsController#new as HTML
  [1m[36mUser Load (1.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 9ms (ActiveRecord: 1.3ms | Allocations: 1887)


Started GET "/" for ::1 at 2021-02-14 23:57:31 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 1.5ms | Allocations: 7)
Completed 200 OK in 15ms (Views: 13.7ms | ActiveRecord: 0.0ms | Allocations: 462)


Started GET "/" for ::1 at 2021-02-14 23:57:42 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 20.5ms | Allocations: 178)
Completed 200 OK in 40ms (Views: 38.5ms | ActiveRecord: 0.0ms | Allocations: 936)


Started GET "/users/sign_up" for ::1 at 2021-02-14 23:57:53 -0600
Processing by Devise::RegistrationsController#new as HTML
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 8ms (ActiveRecord: 0.6ms | Allocations: 1871)


Started GET "/" for ::1 at 2021-02-14 23:57:53 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.2ms | Allocations: 7)
Completed 200 OK in 3ms (Views: 2.4ms | ActiveRecord: 0.0ms | Allocations: 444)


Started GET "/users/sign_up" for ::1 at 2021-02-14 23:58:09 -0600
Processing by Devise::RegistrationsController#new as HTML
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 21ms (ActiveRecord: 0.6ms | Allocations: 1881)


Started GET "/" for ::1 at 2021-02-14 23:58:09 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.6ms | Allocations: 7)
Completed 200 OK in 3ms (Views: 2.5ms | ActiveRecord: 0.0ms | Allocations: 445)


Started GET "/users/sign_up" for ::1 at 2021-02-14 23:58:22 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 1.8ms | Allocations: 189)
  Rendered devise/shared/_links.html.erb (Duration: 4.9ms | Allocations: 550)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 35.0ms | Allocations: 6426)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 89ms (Views: 87.7ms | ActiveRecord: 0.0ms | Allocations: 14947)


Started GET "/users/sign_up" for ::1 at 2021-02-14 23:58:35 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.6ms | Allocations: 189)
  Rendered devise/shared/_links.html.erb (Duration: 1.1ms | Allocations: 539)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 51.7ms | Allocations: 2270)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 79ms (Views: 78.3ms | ActiveRecord: 0.0ms | Allocations: 8818)


Started GET "/users/sign_up" for ::1 at 2021-02-15 00:02:24 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.1ms | Allocations: 15)
  Rendered devise/shared/_links.html.erb (Duration: 1.7ms | Allocations: 172)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 17.0ms | Allocations: 1185)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 72ms (Views: 55.0ms | ActiveRecord: 8.2ms | Allocations: 11180)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:02:26 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:02:26 -0600
Started GET "/users/auth/google_oauth2/callback?state=144011813b0e23c3ee2fa67864e29a1021decaee978a1a67&code=4%2F0AY0e-g5oGkOXYyktN7FIE8i_RqXNkRW_Kjykjf8CrWnOuyKj4ai04mjo5ImD-h2jq9c3Fw&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=consent" for ::1 at 2021-02-15 00:02:36 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2/callback?state=144011813b0e23c3ee2fa67864e29a1021decaee978a1a67&code=4%2F0AY0e-g5cunPKMHTihGHgRP8PueAdD-cOe_vymW6oESp4QByZL5wjqUgD-9j2WXxc3DRuQw&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none" for ::1 at 2021-02-15 00:04:36 -0600
  [1m[35m (2.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2/callback?state=144011813b0e23c3ee2fa67864e29a1021decaee978a1a67&code=4%2F0AY0e-g5TW0eX3sv-RHcWapCrMLmehixZyyJqIh8vgTc2ERDOXvG1FvBELlKSed_0Rc7TSg&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none" for ::1 at 2021-02-15 00:04:38 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:04:42 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:04:42 -0600
Started GET "/users/auth/google_oauth2/callback?state=ab3cd6a272be2f14a6bb7df788d2bae12e86cbe644e22aa3&code=4%2F0AY0e-g7njTVS6yGVEZ4NZ2EWdBuHylM6DyWQtDRx0ep1x8TLMoYd1loZ8H4EXB7j72OmYA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none" for ::1 at 2021-02-15 00:04:43 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:06:30 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:06:30 -0600
Started GET "/users/auth/google_oauth2/callback?state=531a79cbcea9fd9eb4cb993c5521ae6de32a88b0605003c8&code=4%2F0AY0e-g7-wNSBQHQKSsj5QS1j5XksLIGhhDtHkaOFEOCSlKDLe-LtSgbafTKCQr8IIgHYkQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none" for ::1 at 2021-02-15 00:06:30 -0600
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:14:42 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:14:42 -0600
Started GET "/users/auth/google_oauth2/callback?state=80b733325c11d1e6ed9048057a0f64e9fdc51ecdefd92156&code=4%2F0AY0e-g7TSd4sXPx_yDp0eebuTNCGNS9vbEFf8EOc9fjIGuVMXM87mm301Se6sAnCfo324g&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none" for ::1 at 2021-02-15 00:14:42 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:18:01 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:18:01 -0600
Started GET "/users/auth/google_oauth2/callback?state=299eb6419c2da845ab9f993b5cd1c20bd807875847c11491&code=4%2F0AY0e-g4bSjJ48Ax2YYpxCs6yho-_52VcBhNex72YtaFknOk6WMbSu_hm0HPqrHGoOe5U_Q&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none" for ::1 at 2021-02-15 00:18:01 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started POST "/__web_console/repl_sessions/d87ffcc6f3646bc53e0338ba9d6f6cd6/trace" for ::1 at 2021-02-15 00:19:34 -0600
Started POST "/__web_console/repl_sessions/d87ffcc6f3646bc53e0338ba9d6f6cd6/trace" for ::1 at 2021-02-15 00:19:36 -0600
Started GET "/users/auth/google_oauth2/callback" for ::1 at 2021-02-15 00:20:39 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/edit" for ::1 at 2021-02-15 00:24:58 -0600
Processing by Devise::RegistrationsController#edit as HTML
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.0ms | Allocations: 406)


Started GET "/users/sign_in" for ::1 at 2021-02-15 00:24:58 -0600
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (Duration: 2.6ms | Allocations: 1182)
  Rendered devise/sessions/new.html.erb within layouts/application (Duration: 13.5ms | Allocations: 3791)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 133ms (Views: 106.4ms | ActiveRecord: 17.6ms | Allocations: 18285)


Started GET "/users" for ::1 at 2021-02-15 00:25:09 -0600
  
ActionController::RoutingError (No route matches [GET] "/users"):
  
actionpack (6.0.3.5) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.5) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.5) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.5) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.5) lib/rails/engine.rb:527:in `call'
puma (4.3.7) lib/puma/configuration.rb:228:in `call'
puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
puma (4.3.7) lib/puma/server.rb:472:in `process_client'
puma (4.3.7) lib/puma/server.rb:328:in `block in run'
puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/users/sign_up" for ::1 at 2021-02-15 00:25:57 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.4ms | Allocations: 196)
  Rendered devise/shared/_links.html.erb (Duration: 1.0ms | Allocations: 580)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 7.5ms | Allocations: 2445)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 32ms (Views: 20.9ms | ActiveRecord: 4.4ms | Allocations: 13363)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:25:58 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:25:58 -0600
Started GET "/users/auth/google_oauth2/callback?state=e94dd39d4a9b524e322b7da6513ba91106241fa9aedcbc6f&code=4%2F0AY0e-g6Ssri2dQCr0r-ncj9q5HNKLVZoGX_hepdbLCWpItYHCAarGPgB3RvdopgvLcqlSQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none" for ::1 at 2021-02-15 00:25:58 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/sign_up" for ::1 at 2021-02-15 00:26:07 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered devise/shared/_links.html.erb (Duration: 0.3ms | Allocations: 172)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 3.7ms | Allocations: 1185)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 27ms (Views: 16.1ms | ActiveRecord: 3.5ms | Allocations: 10879)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:26:08 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:26:08 -0600
Started GET "/users/auth/google_oauth2/callback?state=c4b7ce1c5b45306d26d9d824d595fb034a2b7bce617411df&code=4%2F0AY0e-g4FYLhwxTt8mLOEHyw1TuHui2adtIkC0WGM38Jmc5yN4jvFNrwAlvKLMLWovRxLvw&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none" for ::1 at 2021-02-15 00:26:09 -0600
  
NoMethodError (undefined method `info' for nil:NilClass):
  
app/models/user.rb:5:in `from_google'
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (1.6ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.4ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (1.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8536163733643263690)[0m
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.2ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_advisory_unlock(8536163733643263690)[0m
  [1m[35m (1.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Started GET "/users/sign_up" for ::1 at 2021-02-15 00:31:04 -0600
Processing by Devise::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered devise/shared/_links.html.erb (Duration: 0.4ms | Allocations: 172)
  Rendered devise/registrations/new.html.erb within layouts/application (Duration: 4.0ms | Allocations: 1185)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 29ms (Views: 16.9ms | ActiveRecord: 4.1ms | Allocations: 10870)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:31:06 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:31:06 -0600
Started GET "/users/auth/google_oauth2/callback?state=38e82af8fce79749fb6c6eb3721d4cdef050317ba364bb0c&code=4%2F0AY0e-g79b52TWtAmK8qJNh_QoR_VnX5tPi8je9EZ5EgFEuy_CU9IrIM2hHGjZbgD4Jv_UA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none" for ::1 at 2021-02-15 00:31:06 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
Started GET "/users/sign_in" for ::1 at 2021-02-15 00:31:11 -0600
Processing by Devise::SessionsController#new as HTML
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (Duration: 0.3ms | Allocations: 223)
  Rendered devise/sessions/new.html.erb within layouts/application (Duration: 6.0ms | Allocations: 1420)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 20ms (Views: 19.1ms | ActiveRecord: 0.0ms | Allocations: 7435)


Started POST "/users/sign_in" for ::1 at 2021-02-15 00:31:14 -0600
Processing by Devise::SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"XJ/gJ6zu7//LTAXFP537dd7RaAb5d3T+DseHVkT6U77+03o5W6z+KzvyC1YHMwtuUXrpERp/yvfndEF8dM2xHg==", "user"=>{"email"=>"entao2000@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
  [1m[36mUser Load (3.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["email", "entao2000@gmail.com"], ["LIMIT", 1]]
Redirected to http://localhost:3000/users/edit
Completed 302 Found in 234ms (ActiveRecord: 3.6ms | Allocations: 5047)


Started GET "/users/edit" for ::1 at 2021-02-15 00:31:14 -0600
Processing by Devise::RegistrationsController#edit as HTML
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  Rendering devise/registrations/edit.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered devise/registrations/edit.html.erb within layouts/application (Duration: 3.3ms | Allocations: 1840)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 19ms (Views: 15.7ms | ActiveRecord: 0.3ms | Allocations: 8575)


Started GET "/users/sign_in" for ::1 at 2021-02-15 00:31:24 -0600
Processing by Devise::SessionsController#new as HTML
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 9ms (ActiveRecord: 0.5ms | Allocations: 1897)


Started GET "/" for ::1 at 2021-02-15 00:31:24 -0600
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/entao/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/templates/rails/welcome/index.html.erb (Duration: 6.5ms | Allocations: 183)
Completed 200 OK in 11ms (Views: 8.8ms | ActiveRecord: 0.0ms | Allocations: 974)


Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:31:31 -0600
Started GET "/users/auth/google_oauth2" for ::1 at 2021-02-15 00:31:31 -0600
Started GET "/users/auth/google_oauth2/callback?state=ca6663ba3d1537354305adfd65ec54d1f96b223384861d31&code=4%2F0AY0e-g4_vHTJwcES7NoViPdefUz_1YNToaFgnAlJWmkbs9S5lI6NSyFY6uqFRIsGMpViKg&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none" for ::1 at 2021-02-15 00:31:32 -0600
  
NameError (undefined local variable or method `request' for OmniauthCallbacksController:Class
Did you mean?  require):
  
app/controllers/omniauth_callbacks_controller.rb:2:in `<class:OmniauthCallbacksController>'
app/controllers/omniauth_callbacks_controller.rb:1:in `<main>'
